# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sigmoid_IP_2/sigmoid_IP.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sigmoid_IP || ORIG_REF_NAME==sigmoid_IP} -quiet] -quiet
